### PR TITLE
Add support for setting activity type

### LINKED ISSUE #251: Adding support for custom activity type
Discord Rich Presence [now supports](https://x.com/advaithj1/status/1816655583107510517?s=46) activities other than just „Playing”. Support for those could be potentially implemented into this library as well?
https://github.com/discordjs/RPC/pull/149

### PR DESCRIPTION
**Pull request by na-2n**
Fixes #251

### CODE REVIEW

**Comment by na-2n** [comment]
went a bit out of scope of this pr and also cleaned up some duplicate code, if unwanted I'll revert it

**Comment by na-2n** [comment]
bump

**Review by SapphicMoe — APPROVED** [review]

**Review by ItsTatsuya — APPROVED** [review]

**Review by Lachee — APPROVED** [review]
This is a much better way to handle the updates.

**Comment by sll552** [comment]
Hi,
this is a much appreciated addition, would it be possible to release a new version? thx ☺️

**Comment by pkg-dot-zip** [comment]
Like @sll552 I would love this to be included in a new release soon. Thank you!

**Comment by sdasda7777** [comment]
Similarly, I would also appreciate being able to use this.

**Pull request merged**
